name: Create BHTikTokPlusPlus

on:
  workflow_dispatch:
    inputs:
      decrypted_ipa_url:
        description: 'Direct URL to decrypted TikTok IPA'
        required: true
      tweaks:
        description: 'Tweaks to enable (leave empty for all)'
        required: false
        default: ''

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Decrypted IPA
        run: |
          curl -L "${{ inputs.decrypted_ipa_url }}" -o TikTok.ipa

      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"

      - name: Build Tweak
        run: |
          make package

      - name: Upload BHTikTokPlusPlus IPA
        uses: actions/upload-artifact@v4
        with:
          name: BHTikTokPlusPlus
          path: "*.ipa"
          retention-days: 7
